### ISSUE TITLE
nosetests: error: no such option: --goober

### ISSUE THREAD

**Issue by p00j4** [dustinkeitel/goober#1]
hi @dustinkeitel : thanks a lot for writing this, however I think i'm missing something in configuration.
**Error**: nosetests: error: no such option: --goober
```
Python 2.7.11
nosetests version 1.3.7
MAC osx: 10.10.5
```

**My Settings:**
setup worked perfectly still goober as option is not enabled, am I missing any more steps?
output from "python  setup.py install"

<img width="859" alt="screen shot 2017-02-06 at 4 11 11 pm" src="https://cloud.githubusercontent.com/assets/6470509/22643969/ad30e3f6-ec86-11e6-9e74-2bdf21fdb1ea.png">
<img width="581" alt="screen shot 2017-02-06 at 4 23 26 pm" src="https://cloud.githubusercontent.com/assets/6470509/22644399/6ac460fe-ec88-11e6-8133-4413ad0b0595.png">

**Comment by dustinkeitel** [comment]
What happens if you `cd` into the goober repo that you cloned and run `pip install -e .`?

**Comment by p00j4** [comment]
perfect! thank you.
this makes it work. however can you please help me understand what it just did which setup install didn't do? like what it looks to me is, it has run "develop" instead of "install" which is like sym-link the egg file sort of, is it?

<img width="662" alt="screen shot 2017-02-07 at 10 56 37 am" src="https://cloud.githubusercontent.com/assets/6470509/22678931/1e79d214-ed24-11e6-85c3-943c55f62542.png">


anyway, not an issue so closing it
@dustinkeitel please have look at https://github.com/dustinkeitel/goober/pull/2 & https://github.com/dustinkeitel/goober/pull/3

**Comment by p00j4** [comment]
not an issue so closing it
@dustinkeitel please have look https://github.com/dustinkeitel/goober/pull/2
